#spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017
#      database: airecommendationfitness
#
#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: activity-processor-final
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#
#
#
#gemini:
#  api:
#    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent
#    key: ${GEMINI_KEY}
#
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true
#
#server:
#  port: 8083
#
#
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: airecommendationfitness


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: activity-processor-final
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


kafka:
  topic:
    name: fitness-activity-topic

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
    key: ${GEMINI_KEY}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8083